inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "redis-objects-periodical.gemspec"

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - "lib/redis-objects-periodical.rb"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 4
