version: '3'

services:
  ruby:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/my_app
      - bundle:/usr/local/bundle
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  bundle:
